spring:
   datasource:
     driverClassName: com.mysql.jdbc.Driver
     url: jdbc:mysql://mysql:3306/sample
     username: omar
     password: pass
   jpa:
      hibernate.ddl-auto: update
      generate-ddl: true 
      show-sql: true
      database-platform : org.hibernate.dialect.MySQLDialect